# Link repository with Travis CI
# https://travis-ci.org/

# Whitelist gh-pages branch
branches:
  only:
    - master

# Set the language
language: bash

os:
  - osx
  - linux

env:
  global:
    - PATH=$TRAVIS_BUILD_DIR/usr/bin/:$PATH
    - PATH=/Library/TeX/texbin:$PATH

python:
  # We don't actually use the Travis Python, but this keeps it organized.
  # - "2.7"
  # - "3.5"
  - "3.6"
  # - "3.7"
  # - "3.8"

before_install:
  # Install conda
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      OS_NAME=MacOSX
    elif [ "$TRAVIS_OS_NAME" = "linux" ]; then
      OS_NAME=Linux
    fi
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-MacOSX-x86_64.sh -O miniconda.sh
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # The install of mactex...takes a long time: ~20mins
  # investigate using a docker image to save time?:
  #     https://tex.stackexchange.com/questions/398830/how-to-build-my-latex-automatically-using-travis-ci
  - |
    if [ "$TRAVIS_OS_NAME" = "osx" ]; then
      brew install --cask mactex
    elif [ "$TRAVIS_OS_NAME" = "linux" ]; then
      apt-get install texlive
    fi
  - sudo tlmgr update --self

install:
  # Make python venv
  - conda create -n phd python=${PYTHON_VERSION} pandoc
  - conda activate phd
  # Installs both python and texlive dependencies
  - make install
  # Info
  - conda list
  - pip list
  - python --version
  - pandoc --version
  - tlmgr --version
  - latex --version

# Attempt to create all document output types
script:
  - make help
  - make tex
  - cat pandoc.tex.log
  - make pdf
  - cat pandoc.pdf.log
  - make html
  - cat pandoc.html.log
  - make docx
  - cat pandoc.docx.log
  - make all
  - cat pandoc.*.log
